// Generated by CoffeeScript 1.6.2
var CSSParser, Main, main,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

CSSParser = (function() {
  CSSParser.prototype.index = {};

  function CSSParser() {
    this.ss = document.styleSheets[1];
    this.buildIndex();
  }

  CSSParser.prototype.buildIndex = function() {
    var i,
      _this = this;

    i = 0;
    return _.each(this.ss.rules, function(rule) {
      var color, raw, selector;

      raw = rule.cssText.split('{');
      selector = raw[0].trim().substr(1);
      if (_this.isValidRule(selector)) {
        color = raw[1].split('color:')[1];
        color = color.substr(0, color.indexOf(';')).trim();
        _this.index[selector] = {
          color: color,
          index: i
        };
      }
      return i++;
    });
  };

  CSSParser.prototype.isValidRule = function(selector) {
    return selector.length === 3;
  };

  CSSParser.prototype.modifyColor = function(selector, newColor) {
    if ((this.index[selector] != null)) {
      this.index[selector].color = newColor;
      return this.ss.rules[this.index[selector].index].style.color = newColor;
    }
  };

  CSSParser.prototype.validateColor = function(c) {
    if (c.charAt(0) === '#') {
      if (c.length !== 4 && c.length !== 7) {
        return false;
      }
    }
    return true;
  };

  return CSSParser;

})();

Main = (function() {
  function Main() {
    this.updateColor = __bind(this.updateColor, this);    this.css = new CSSParser(document.styleSheets[1]);
    this.populateForm();
  }

  Main.prototype.updateColor = function(hex) {
    if (hex == null) {
      hex = 'random';
    }
    if (hex === 'random') {
      hex = this.getRandomHex();
    }
    return document.styleSheets[0].rules[50].style.color = hex;
  };

  Main.prototype.getRandomHex = function() {
    return '#' + Math.floor(Math.random() * 16777215).toString(16);
  };

  Main.prototype.populateForm = function() {
    var _this = this;

    return _.each(this.css.index, function(obj, selector) {
      var el;

      el = _this.getFormInput(selector);
      if (el.length > 0) {
        el.val(obj.color);
        return el.keyup(function() {
          return _this.respondToFormChange(el, obj, selector);
        });
      }
    });
  };

  Main.prototype.respondToFormChange = function(el, obj, selector) {
    var val;

    val = el.val();
    if (this.css.validateColor(val)) {
      el.removeClass('error');
      return this.css.modifyColor(selector, el.val());
    } else {
      return el.addClass('error');
    }
  };

  Main.prototype.getFormInput = function(selector) {
    return $("\#" + selector + "-input");
  };

  return Main;

})();

main = {};

$(function() {
  if (typeof prettyPrint !== "undefined" && prettyPrint !== null) {
    prettyPrint();
  }
  return window.main = new Main();
});

/*
//@ sourceMappingURL=main.map
*/
